### PR TITLE
use serialized message in callback

### PR DESCRIPTION
**Pull request by Karsten1987**
connects to https://github.com/ros2/rclcpp/pull/1090

### CODE REVIEW

**Comment by dirk-thomas** [comment]
In combination with ros2/rclcpp#1092.

**Comment by j-rivero** [comment]
> Test running at [Build Status](https://ci.ros2.org/job/ci_osx/8512/)

Problems with cmake configuration should be fixed by https://github.com/ament/ament_cmake/pull/248

**Comment by j-rivero** [comment]
Copied from https://github.com/ros2/rclcpp/pull/1090#issuecomment-618463293 , The builds are running this PR branch:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10443/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5936/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8518/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10325/)

**Comment by dirk-thomas** [comment]
@j-rivero The Windows build is incorrect. Please don't copy the same links into multiple places since then multiple locations needs to be updated / kept in sync. The jobs for this branch are in the referenced PR https://github.com/ros2/rclcpp/pull/1092#issuecomment-618514341

**Comment by ivanpauno** [comment]
See CI [here](https://github.com/ros2/rclcpp/pull/1092#issuecomment-618514341) and comment [here](https://github.com/ros2/rclcpp/pull/1092#issuecomment-618560290).
Merging!

**Pull request merged**
