### PR TITLE
add multibyte tests to Primitives

### PR DESCRIPTION
**Pull request by k-okada**
as suggested at https://github.com/ros2/rosidl/issues/208#issuecomment-287262096

connects to ros2/ros2#384

### CODE REVIEW

**Comment by dirk-thomas** [comment]
* [Build Status](http://ci.ros2.org/job/ci_linux/2328/)
* [Build Status](http://ci.ros2.org/job/ci_osx/1787/)
* [Build Status](http://ci.ros2.org/job/ci_windows/2425/)

**Comment by dirk-thomas** [comment]
You branch doesn't compile against the latest master. Please rebase your fork to the latest HEAD.

**Comment by k-okada** [comment]
rebased, but I think we need https://github.com/ros2/rosidl/pull/209 to pass the test.

**Comment by mikaelarguedas** [comment]
indeed we'll need https://github.com/ros2/rosidl/pull/209 for the test to pass. Though this branch of rosidl needs to be rebased as well and [the PyUUnicode typo](https://github.com/ros2/rosidl/pull/209/files#diff-b2f2e0cf38761b5172a69e11d4d8a842R135) will need to be fixed in order for it to compile

**Comment by dirk-thomas** [comment]
* [Build Status](http://ci.ros2.org/job/ci_linux/2333/)
* [Build Status](http://ci.ros2.org/job/ci_osx/1789/)
* [Build Status](http://ci.ros2.org/job/ci_windows/2434/)

**Comment by dirk-thomas** [comment]
The patches seem to fail several tests.

**Comment by k-okada** [comment]
Should be pass test on first commit  
- [Build Status](http://ci.ros2.org/job/ci_linux/2443/)
- [Build Status](http://ci.ros2.org/job/ci_linux/1890/)
- [Build Status](http://ci.ros2.org/job/ci_linux/2563/)
And failed with multibyte test, only for python, I have confirmed this could be fixed by https://github.com/ros2/rosidl/pull/209  on my local environment 
- [Build Status](http://ci.ros2.org/job/ci_linux/2444/)
- [Build Status](http://ci.ros2.org/job/ci_linux/1891/)
- [Build Status](http://ci.ros2.org/job/ci_linux/2564/)

**Comment by jacobperron** [comment]
Closing due to age and inactivity.

**Pull request closed without merging**
