### PR TITLE
Add tests for BoundedPlainSequences

### PR DESCRIPTION
**Pull request by sloretz**
`test_communication` makes tests for every message type in `test_interface_files`. This PR adds code support in the tests for the new message.

Requires https://github.com/ros2/rcl_interfaces/pull/125 - together they should fix the nightlies

### CODE REVIEW

**Comment by sloretz** [comment]
CI (build: `--packages-up-to test_communication` test: ` --packages-select test_msgs test_communication`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14994/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9733/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12681/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15156/)

**Comment by scpeters** [comment]
I take it the build.ros.org CI failed because it's using the released versions of dependencies instead of building https://github.com/ros2/rcl_interfaces/pull/125 from source?

**Comment by clalancette** [comment]
> I take it the build.ros.org CI failed because it's using the released versions of dependencies instead of building [ros2/rcl_interfaces#125](https://github.com/ros2/rcl_interfaces/pull/125) from source?

That's correct.  We'll need to do a release of `rosidl` into Rolling to resolve that.

**Review by clalancette — APPROVED** [review]

**Review by hidmic — APPROVED** [review]

**Comment by hidmic** [comment]
I can roll out the Rolling releases once https://github.com/ros2/rcl_interfaces/pull/125 is in. https://github.com/ros2/rmw_implementation/pull/193 needs them.

**Pull request merged**
