### PR TITLE
Revert "Revert "Replace deprecated spin_until_future_complete""

### PR DESCRIPTION
**Pull request by wjwwood**
Reverts ros2/system_tests#504

Merge this once related prs are ready.

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
either @wjwwood or @audrow can i have the permission to push this repo? i want to rebase this one.

**Comment by audrow** [comment]
> either @wjwwood or @audrow can i have the permission to push this repo? i want to rebase this one.

I'm not sure how to give you access, but I rebased the branch 👍

**Comment by christophebedard** [comment]
I've opened #541 to replace this PR.

**Comment by christophebedard** [comment]
This can be closed, see https://github.com/ros2/system_tests/pull/541#issuecomment-2035716235

**Pull request closed without merging**
