### PR TITLE
Use new interface definitions

### PR DESCRIPTION
**Pull request by jacobperron**
Interface definitions for testing have been consolidated into a common package, [test_interface_files](https://github.com/ros2/test_interface_files).
They have been refactored in an effort to reduce the number of interfaces and also renamed to follow IDL terminology.

This change switches over the tests to use the new interface definitions.

Connects to https://github.com/ros2/rcl_interfaces/issues/58

### CODE REVIEW

**Comment by jacobperron** [comment]
Preliminary test of `test_communications` to catch any issues:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6852/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3142/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5633/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6671/)

I realized I should also update `test_cli_remapping` and `test_security` for a full CI to pass.

**Comment by jacobperron** [comment]
Rebased on master to get launch testing changes.

**Comment by jacobperron** [comment]
CI retriggered including changes in the following connected PRs:

- rosidl_runtime_py ros2/rosidl_python#49
- rcl ros2/rcl#427
- rclpy ros2/rclpy#332
- test_msgs #77

**Comment by jacobperron** [comment]
@dirk-thomas PTAL at c1c41b2

I'm not sure why, but `BoundedSequences.msg` has different serialized sizes dependent on the RMW implementation. `BasicTypes.msgs` appears for consistent.

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6879/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3163/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5650/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6701/)

**Comment by dirk-thomas** [comment]
https://ci.ros2.org/job/ci_windows/6701/warnings43Result/

It looks like the min value of int32 needs the same treatment as the 64 bit one.

**Comment by jacobperron** [comment]
> It looks like the min value of int32 needs the same treatment as the 64 bit one.

Fix https://github.com/ros2/rosidl/pull/375 and CI:
[Build Status](https://ci.ros2.org/job/ci_windows/6704/)

**Pull request merged**
