### PR TITLE
Add tests for ros2action and ros2msg

### PR DESCRIPTION
**Pull request by ivanpauno**
The idea of this is start increasing testing coverage in all the `ros2cli` related command line tools, to avoid manual testing in the next release.

### CODE REVIEW

**Comment by ivanpauno** [comment]
Added test for `ros2msg` in https://github.com/ros2/system_tests/pull/372/commits/af0fd2957d6373fd97a4eadc89a2de5fb90f6b44.
Refactored in https://github.com/ros2/system_tests/pull/372/commits/2149de3cf0a78714b4de216eaa029d8735509705 for avoiding duplicated code.

I will add test for the remaining verbs in separated PRs, after this one gets approved.

**Comment by jacobperron** [comment]
Do these tests necessarily need to be in system_tests, or is it possible for them to live closer to the code being tested?

**Comment by ivanpauno** [comment]
> Do these tests necessarily need to be in system_tests, or is it possible for them to live closer to the code being tested?

Yeah, maybe it's better. I added them here because these are more like "integration tests" than unit tests. But I think that that only justifies creating a new package (`test_ros2cli`), than moving them here.

If you agree, I will close this one and open a new PR in `ros2cli`.

**Comment by jacobperron** [comment]
IMO it makes sense to move the package to ros2/ros2cli (similar to how launch_ros has [integration tests](https://github.com/ros2/launch_ros/tree/master/test_launch_ros) in the same repo). But, it would be good to get additional input from @ros2/team.

**Comment by wjwwood** [comment]
I'm not sure why they were separated, but it may be due to these tests having a separate dependency on some message packages that otherwise would not be needed to build that repository. Personally, if it remains in a separate package, there's no reason that I know of to avoid having them in the same repository. But others might remember why it is this way better than me?

**Comment by ivanpauno** [comment]
Closed in favor of https://github.com/ros2/ros2cli/pull/287.

**Comment by mjcarroll** [comment]
@ivanpauno can we delete the branch?

**Pull request closed without merging**
