### PR TITLE
add test for set_parameters_atomically

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Connects to ros2/rclcpp#494

leaving in progress until ci comes back green

### CODE REVIEW

**Comment by dhood** [comment]
Have you thought about adding a [local test too](https://github.com/ros2/system_tests/blob/72cc768aa848611a16598fbbb55c5fbc5958c651/test_rclcpp/test/test_local_parameters.cpp#L73)?

**Comment by mikaelarguedas** [comment]
Yeah, I didnt see much benefit so focused on showing that the expected usage (remote) would stop segfaulting once https://github.com/ros2/rclcpp/pull/494 is merged.

If you think covering the async and local cases are requirement for getting this merged I can try revisiting it later this week.

**Comment by dhood** [comment]
it'd be good to have the rest of the tests, but I understand it's not the highest priority at the moment!

**Comment by mikaelarguedas** [comment]
> it'd be good to have the rest of the tests, but I understand it's not the highest priority at the moment!

Ticketed at #282 as I'm not sure I'll have time to address this this week, but I'll try to get around doing it.

**Pull request merged**
