### PR TITLE
add test to cover messages with an array of sub messages

### PR DESCRIPTION
**Pull request by dirk-thomas**
This tests covers the case which currently fails in #14.

I will wait with the merge until a fix has been committed to `rmw_connext_dynamic_cpp`.

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
And another set of tests with static arrays of sub messages.

**Comment by wjwwood** [comment]
+1 again.

**Comment by jacquelinekay** [comment]
+1

**Pull request merged**
