### PR TITLE
fix generation of tests with multiple executables

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fix wrong CMake variable to reenabled tests with multiple executables. Numerous of the tests are currently failing:

* http://ci.ros2.org/job/ci_linux/1269/
* http://ci.ros2.org/job/ci_osx/1015/
* http://ci.ros2.org/job/ci_windows/1303/

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Now the failing tests boild down to ros2/rclcpp#219: http://ci.ros2.org/job/ci_linux/1274/testReport/

**Comment by dirk-thomas** [comment]
This seems to be a bug in OpenSplice itself: PrismTech/opensplice#25

**Comment by jacquelinekay** [comment]
+1

**Comment by mikaelarguedas** [comment]
lgtm, all tests pass locally on linux with #126 on top of this PR.
+1

**Comment by dirk-thomas** [comment]
* I removed the usage of `RCL_ASSERT_RMW_ID_MATCHES` for multi target tests since it doesn't work as-is.
* Since we are waiting for a fix for the OpenSplice bug I disabled these tests for now.
* I also disabled the service tests across vendors for FastRTPS.

* [Build Status](http://ci.ros2.org/job/ci_linux/1376/)
* [Build Status](http://ci.ros2.org/job/ci_osx/1072/) all but one message type fail to be published by FastRTPS and subscribed by OpenSplice on OS X
* [Build Status](http://ci.ros2.org/job/ci_windows/1381/)

**Comment by dirk-thomas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/1379/) FastRTPS doesn't talk to other vendors with the DynamicArrrayPrimitives message
* OS X [Build Status](http://ci.ros2.org/job/ci_osx/1076/) in addition to the failing cases on Linux: pub / sub between FastRTPS and OpenSplice fails (in both directions for all message types)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/1388/) in addition to the failing cases on Linux: Connext dynamic subscriber for various message types

**Comment by dirk-thomas** [comment]
After some discussion offline we came to the conclusion to merge this for now. Having all failing tests visible for the upcoming "test-fixing-hackathon" is beneficial and it makes it easier to work on fixes for the separate kind of problems.

If we can't address some of the failing tests due to bugs in third-party packages we might disable and ticket them (similar as for the OpenSplice publishing bug).

**Comment by mikaelarguedas** [comment]
In the optics of having all the failing test visibles. Should we also merge #125 ?

**Comment by dirk-thomas** [comment]
@mikaelarguedas Can you please run CI for #125 first to see what the effect is.

**Pull request merged**
