### PR TITLE
separate callback_group from subscription options

### PR DESCRIPTION
**Pull request by fujitatomoya**
aligned with https://github.com/ros2/rclcpp/pull/1833

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos requesting review.

**Review by iuhilnehc-ynos — APPROVED** [review]
LGTM

**Review by iuhilnehc-ynos — APPROVED** [review]
LGTM

**Comment by fujitatomoya** [comment]
@adityapande-1995 @sloretz could you take a look?

**Review by wjwwood — APPROVED** [review]

**Comment by fujitatomoya** [comment]
closing because of https://github.com/ros2/rclcpp/pull/1833#issuecomment-1131095686

**Pull request closed without merging**
