### PR TITLE
add tests for publish/subscribe in a single process

### PR DESCRIPTION
**Pull request by dirk-thomas**
This test currently fails with the Connext rwm implementations.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please review this as well as the referenced PR on `rmw_connext`.

**Comment by wjwwood** [comment]
lgtm

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
This was auto-closed when the referenced PR was merged.

**Comment by esteve** [comment]
+1

**Comment by dirk-thomas** [comment]
Since the test binary only uses the return code to signal success / failure it needs to explicitly generate a XUnit result file: 3f0ab3f6f1389a473841bfbaa6d214d199a533e5

**Pull request merged**
