### PR TITLE
adding tests for intra process communications

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/ros2#59

### CODE REVIEW

**Comment by jacquelinekay** [comment]
Are you going to test the case of multiple nodes with intra-process enabled here, or the case of 1 node with intra-process enabled and 1 with intra-process disabled?

**Comment by wjwwood** [comment]
Yes....

Let's push those for round 2 where I actually implement subscription filtering because this test is horribly naive as is. So as most this test is testing that it just works in the best scenario.

I'll add a note on https://github.com/ros2/ros2/issues/91 so we don't forget: https://github.com/ros2/ros2/issues/91#issuecomment-132781068

**Comment by jacquelinekay** [comment]
Sounds good.

**Comment by wjwwood** [comment]
I should say this test is horribly naive as is because there is no subscription filtering. Anything more complex would likely break.

**Comment by esteve** [comment]
+1

**Pull request merged**
