### PR TITLE
Add testing for additional messages to test ros2interface

### PR DESCRIPTION
**Pull request by audrow**
Part of the fix for ros2/ros2cli#541.

### CODE REVIEW

**Comment by audrow** [comment]
This set of PRs seems to pass CI without breaking downstream packages.  I'll run the rest of CI once these PRs are reviewed.
[Build Status](http://ci.ros2.org/job/ci_linux/11854/)

**Comment by dirk-thomas** [comment]
What use case are these new tests covering which the existing tests don't?

**Comment by audrow** [comment]
They add the following to the interface definitions in `test_interface_files` and `test_msgs`:
* Multiple nesting levels for actions and services, without using `builtin_interfaces`
* Bounded sequences testing for actions and services
* Constants for services and actions
* Comments 
  * Full line comments (including comments at multiple nesting levels) for services
  * Inline comments for messages, services, and actions
* Empty lines for messages, services, and actions

These inclusions make these interfaces useful for testing `ros2interface`'s `show` command.

**Comment by audrow** [comment]
Closed in favor of https://github.com/ros2/ros2cli/pull/579.

**Pull request closed without merging**
