### PR TITLE
disregard duplicate requests

### LINKED ISSUE #50: Intermittently failing requester/replier test
The test_requester_replier test is flaky on master.

e.g. on a recent test branch, it passed on osx but not Linux:
http://ci.ros2.org/job/ros2_batch_ci_linux/403/testReport/junit/(root)/test_requester_replier_cpp__empty__rmw_connext_dynamic_cpp/test_requester_replier/
http://ci.ros2.org/job/ros2_batch_ci_osx/300/

### PR DESCRIPTION
**Pull request by wjwwood**
fixes #50

### CODE REVIEW

**Comment by wjwwood** [comment]
As I see it, we either have to take this patch to fix #50 or increase the timeout on the requester such that it never encounters this race condition.

**Comment by dirk-thomas** [comment]
If we don't want to check for duplicate requests I would suggest to remove the `received_messages` completely.

**Comment by wjwwood** [comment]
Ok, if we agree on the approach to fix the flaky test then I'll remove it all.

**Comment by wjwwood** [comment]
CI:
- http://ci.ros2.org/job/ros2_batch_ci_linux/407/
- http://ci.ros2.org/job/ros2_batch_ci_osx/304/
- http://ci.ros2.org/job/ros2_batch_ci_windows/453/

**Comment by dirk-thomas** [comment]
+1 (if CI passes as expected)

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
The Windows job has test failures, but are unrelated in difference from the master branch, I ran a master branch job on Windows right after the one for this branch for comparison:

http://ci.ros2.org/job/ros2_batch_ci_windows/454/

**Pull request merged**
