### PR TITLE
test case for spinning before creating subscription

### PR DESCRIPTION
**Pull request by tfoote**
Connects to ros2/rclcpp#179

### CODE REVIEW

**Comment by jacquelinekay** [comment]
This test case passes locally for Opensplice and Connext for me. Should we merge this test case?

**Comment by jacquelinekay** [comment]
Eh, nevermind, doesn't pass with FastRTPS. I'll check it out.

**Comment by jacquelinekay** [comment]
@tfoote, I would guess that you're encountering a problem with nondeterministic thread scheduling here.

I made a single-threaded version of this test case and the test passes on all middlewares. It makes a node, spins a bit, add a subscription, then spins some more and gets the callback.

https://github.com/ros2/system_tests/commit/bb16cadce8be8a4ad3b422e5973bee6b8cd02326

I'm guessing the `spin` thread doesn't ever execute when you run this code for some reason.

**Comment by jacquelinekay** [comment]
ok, after further inspection I observe that the single-threaded case is flaky for Connext.

**Comment by tfoote** [comment]
@jacquelinekay will check if this can be closed.

**Comment by jacquelinekay** [comment]
we have a test case for this in master that passes now. therefore I'm going to close this.

https://github.com/ros2/system_tests/blob/master/test_rclcpp/test/test_subscription.cpp#L402

**Pull request closed without merging**
