### PR TITLE
tests for get_parameter_or and set_parameter_if_not_set

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/rclcpp#309

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@wjwwood ping just to make sure this is still in progress and has not been forgotten when merging https://github.com/ros2/rclcpp/issues/309

**Comment by wjwwood** [comment]
Oops, good catch 😛

**Comment by mikaelarguedas** [comment]
@wjwwood FYI: this PR introduced [new warnings](http://ci.ros2.org/view/nightly/job/nightly_win_deb/420/) on MSVC. It's due to ParameterVariant defining integer parameters as int64 and these tests use `int`

**Comment by wjwwood** [comment]
@mikaelarguedas shoot, I missed that (symptom of not having green jobs normally I guess). I also didn't notice because it was introduced before I started tracking these as the Build cop, so I file the warning as "existing" and to look into it later.

I'll try to avoid that in the future.

**Comment by wjwwood** [comment]
That's frustrating, I could use a concept with a constraint to limit the possible data types for these functions, but I'm not sure those are ready for prime time:

http://en.cppreference.com/w/cpp/language/constraints

I'll open a pr soon to fix it.

**Pull request merged**
