### PR TITLE
Update to C++17

### PR DESCRIPTION
**Pull request by clalancette**

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19494/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14014/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20213/)

**Review by ahcorde — APPROVED** [review]

**Comment by clalancette** [comment]
The test failures is a quite surprising result here.  I'll have to look into it.

**Comment by mjcarroll** [comment]
Looks like many "failed to create participant", could it be a transient thing?

**Comment by clalancette** [comment]
> Looks like many "failed to create participant", could it be a transient thing?

Maybe, but I also just hit that locally.

**Comment by clalancette** [comment]
Here's another CI attempt (only on Linux) with some recent CI changes reverted.  This is just to check whether that makes any difference:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19545/)

**Pull request merged**
