### PR TITLE
Handles msg files with the same name in different subfolders

### PR DESCRIPTION
**Pull request by hidmic**
Connected to ros2/rosidl#301. This pull request tweaks `test_communication` and `test_security` packages to properly handle .msg and .srv definition in action folders.

### CODE REVIEW

**Comment by hidmic** [comment]
Nothing to add, you're spot on. Only downside is that we lose test coverage for generated action messages and services until we get to the point where we can write tests for actions. Changes applied. PTAL.

**Comment by apojomovsky** [comment]
Missed this one as part of yesterday's merge group. Merging now.

**Comment by dirk-thomas** [comment]
@hidmic @apojomovsky Is the branch still needed or can it be deleted?

**Comment by apojomovsky** [comment]
It can be safely deleted @dirk-thomas . My mistake here, I should have deleted it after merging.

**Pull request merged**
